import torch
import pandas as pd
import numpy as np
import json
import os
import re
import emoji # Added import
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from tqdm.auto import tqdm
import sys
import pandas.api.types as ptypes
try:
    from transformers import AutoTokenizer
except ImportError:
    print("ERROR: HuggingFace Transformers library not installed.")
    print("       Please install it: pip install transformers")
    sys.exit(1)
import config

# --- Emoji & Text Cleaning ---
class BasicTextCleaner:
    def clean(self, text):
        """Cleans text, including converting emojis to text descriptions."""
        text = str(text) # Ensure text is string

        # 1. Convert emojis to colon-delimited text descriptions (e.g., ":smiling_face:")
        # Ensure we handle potential errors or None values from emoji lib
        try:
            # Using lang='en' for consistent English descriptions
            demojized_text = emoji.demojize(text, language='en')
        except Exception as e:
            # Fallback to original text if demojization fails
            # print(f"Warning: Error during emoji demojization for text: '{text[:50]}...'. Error: {e}. Skipping demojization.")
            demojized_text = text # Fallback

        # 2. Lowercase the entire text
        text = demojized_text.lower()

        # 3. Process the demojized descriptions: remove colons and replace underscores with spaces.
        # This targets the pattern like :word_word: resulting from step 1 using regex.
        def replace_emoji_description(match):
            # match.group(1) is the content inside colons like "smiling_face_with_smiling_eyes"
            description = match.group(1).replace('_', ' ') # Replace underscores with spaces
            return description

        # Find all occurrences of :...: and replace them using the helper function
        # This is safer as it only processes patterns generated by demojize
        # Use re.IGNORECASE for case-insensitive matching if demojize output varies
        text_processed_emojis = re.sub(r':([a-zA-Z0-9_]+):', replace_emoji_description, text)


        # 4. Remove specific patterns (mentions, urls)
        text_no_mentions_urls = re.sub(r'@\w+', '', text_processed_emojis)
        text_no_mentions_urls = re.sub(r'http\S+|www\S+|https\S+', '', text_no_mentions_urls, flags=re.MULTILINE)


        # 5. Clean up extra whitespace (important after replacements and removals)
        text_cleaned = re.sub(r'\s+', ' ', text_no_mentions_urls).strip()

        return text_cleaned

    def preprocess_batch(self, texts):
        """Applies cleaning to a batch of texts with a progress bar."""
        # Use a list comprehension for efficiency, tqdm will wrap it
        return [self.clean(text) for text in tqdm(texts, desc="Cleaning Text")]

# --- Utility Functions ---
def to_native_type(item):
    """Converts numpy types and pandas timestamps/timedeltas for JSON serialization."""
    if isinstance(item, np.integer): return int(item)
    elif isinstance(item, np.floating): return float(item)
    elif isinstance(item, np.ndarray): return item.tolist() # Handle numpy arrays (like multi-hot labels)
    elif isinstance(item, np.bool_): return bool(item)
    elif isinstance(item, (pd.Timestamp, pd.Timedelta)): return str(item)
    # Handle lists potentially containing numpy types
    elif isinstance(item, list): return [to_native_type(sub_item) for sub_item in item]
    # Handle dictionaries potentially containing numpy types
    elif isinstance(item, dict): return {k: to_native_type(v) for k, v in item.items()}
    return item

def save_label_mappings(label_to_int, int_to_label, filepath=config.LABEL_MAP_PATH):
    """Saves label to integer and integer to label mappings to a JSON file."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    try:
        # Ensure keys are strings for JSON keys, convert values
        label_to_int_serializable = {str(k): to_native_type(v) for k, v in label_to_int.items()}
        int_to_label_serializable = {str(k): to_native_type(v) for k, v in int_to_label.items()}
    except Exception as e:
         print(f"Error converting label map items for serialization: {e}")
         # Fallback to basic string conversion if custom to_native_type fails
         label_to_int_serializable = {str(k): str(v) for k, v in label_to_int.items()}
         int_to_label_serializable = {str(k): str(v) for k, v in int_to_label.items()}

    save_data = {'label_to_int': label_to_int_serializable, 'int_to_label': int_to_label_serializable}
    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(save_data, f, indent=4, ensure_ascii=False)
        print(f"Label mappings saved to {filepath}")
    except Exception as e:
        print(f"Error saving label mappings to {filepath}: {e}")

def load_label_mappings(filepath=config.LABEL_MAP_PATH):
    """Loads label to integer and integer to label mappings from a JSON file."""
    if not os.path.exists(filepath):
        print(f"Label mapping file not found at {filepath}. Returning None.")
        return None, None

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            loaded_data = json.load(f)

        label_to_int = loaded_data.get('label_to_int', {})
        int_to_label_str_keys = loaded_data.get('int_to_label', {})

        # Convert int_to_label keys from string (JSON default) to int
        int_to_label = {}
        for k, v in int_to_label_str_keys.items():
            try:
                int_to_label[int(k)] = v
            except ValueError:
                print(f"Warning: Skipping non-integer key '{k}' in int_to_label map from {filepath}")

        if not label_to_int or not int_to_label:
             print(f"Warning: Loaded label map from {filepath} seems incomplete or empty.")
             return None, None

        # Ensure int_to_label keys are sequential and cover all classes
        num_loaded_classes = len(int_to_label)
        expected_keys = set(range(num_loaded_classes))
        actual_keys = set(int_to_label.keys())

        if expected_keys != actual_keys:
             print(f"Warning: Loaded int_to_label keys from {filepath} are not sequential 0 to N-1.")
             # Attempt to reconstruct based on label_to_int if possible, or warn further
             if len(label_to_int) == num_loaded_classes:
                 print("  Reconstructing int_to_label from label_to_int mapping.")
                 int_to_label = {v: k for k, v in label_to_int.items()}
             else:
                 print("  Cannot reliably reconstruct int_to_label. Proceeding with loaded map, but issues possible.")


        print(f"Label mappings loaded from {filepath}. Num classes: {len(int_to_label)}")
        return label_to_int, int_to_label

    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from {filepath}. File might be corrupted.")
        return None, None
    except Exception as e:
        print(f"Error loading label mappings from {filepath}: {e}")
        import traceback; traceback.print_exc(); # More detailed error
        return None, None


def load_raw_data(filepath, file_format=config.INPUT_FILE_FORMAT, text_col_idx=config.TEXT_COLUMN_INDEX,
                  label_col_idx=config.LABEL_COLUMN_INDEX, col_names=config.COLUMN_NAMES, has_header=config.HAS_HEADER):
    """Loads raw data from file based on format and column config."""
    print(f"Attempting to load raw data from: {filepath} (Format: {file_format})")
    if not filepath or not os.path.exists(filepath):
         print(f"Warning: Data file not found or path is invalid: {filepath}")
         return None

    df = None
    try:
        # pandas read_csv handles tsv if sep='\t'
        read_opts = {'on_bad_lines': 'warn', 'low_memory': False}
        if file_format == "csv":
            header = 0 if has_header else None
            names = None if has_header else col_names
            df = pd.read_csv(filepath, header=header, names=names, **read_opts)
        elif file_format == "tsv":
            header = 0 if has_header else None
            names = None if has_header else col_names
            df = pd.read_csv(filepath, sep='\t', header=header, names=names, **read_opts)
        elif file_format == "jsonl":
             # For JSONL, col_names are the keys in JSON objects
             # We assume keys are 'text' and 'labels' (list of strings)
             df = pd.read_json(filepath, lines=True)
             # Ensure required columns exist
             if 'text' not in df.columns or 'labels' not in df.columns:
                  raise ValueError(f"JSONL file must contain 'text' and 'labels' keys. Found: {list(df.columns)}")
             # Rename columns to match expected 'text' and 'label' (for labels_str processing conceptually)
             # JSONL labels are already lists, so we rename 'labels' to 'label' directly
             df.rename(columns={'labels': 'label', 'text': 'text'}, inplace=True)
             has_header = False # JSONL does not have a header row
             text_col_name = 'text'
             label_col_name = 'label' # This will now hold lists of strings from JSONL
             df_std = pd.DataFrame({'label': df[label_col_name], 'text': df[text_col_name]})

        else:
             raise ValueError(f"Unsupported file format: {file_format}")

        # For CSV/TSV, select the text and label columns by index
        if file_format in ["csv", "tsv"]:
            num_cols = len(df.columns)
            if label_col_idx >= num_cols or text_col_idx >= num_cols:
                 raise IndexError(f"Column index out of bounds (Label: {label_col_idx}, Text: {text_col_idx}). File '{os.path.basename(filepath)}' has {num_cols} columns: {list(df.columns)}. Ensure COLUMN_NAMES is correct if HAS_HEADER is False, or indices are correct if HAS_HEADER is True.")

            text_col_name = df.columns[text_col_idx]
            label_col_name = df.columns[label_col_idx] # This column will contain the comma-separated string
            print(f"  Using columns - Label (comma-sep): '{label_col_name}' (Index {label_col_idx}), Text: '{text_col_name}' (Index {text_col_idx})")
            # Use a temp name for the raw label string column before splitting
            df_std = pd.DataFrame({'labels_str': df[label_col_name], 'text': df[text_col_name]})

        original_rows = len(df_std)
        # Drop rows where the text or label string is NaN/None
        # For JSONL, 'label' is already the list column
        subset_cols_for_dropna = ['text', label_col_name if file_format in ["csv", "tsv"] else 'label']
        df_std = df_std.dropna(subset=subset_cols_for_dropna).reset_index(drop=True)

        rows_dropped = original_rows - len(df_std)
        if rows_dropped > 0: print(f"  Dropped {rows_dropped} rows with NaN values in 'text' or label column.")

        df_std['text'] = df_std['text'].astype(str)

        # For TSV/CSV with comma-separated labels, split the label string into a list
        if file_format in ["csv", "tsv"]:
             # Split comma-separated string into a list of strings
             # Handle potential NaN/empty strings carefully after dropna
             df_std['label'] = df_std['labels_str'].apply(lambda x: [lbl.strip() for lbl in str(x).split(',') if lbl.strip()] if pd.notna(x) and str(x).strip() else [])
             # Drop the temporary labels_str column
             df_std.drop(columns=['labels_str'], inplace=True)
             # Drop rows that result in an empty label list after splitting/cleaning
             original_rows_after_nan_drop = len(df_std)
             df_std = df_std[df_std['label'].apply(lambda x: len(x) > 0)].reset_index(drop=True)
             rows_dropped_empty_list = original_rows_after_nan_drop - len(df_std)
             if rows_dropped_empty_list > 0: print(f"  Dropped {rows_dropped_empty_list} rows with empty label lists after splitting.")

        # For JSONL, the 'label' column already contains lists, ensure types and non-empty
        elif file_format == "jsonl":
             df_std['label'] = df_std['label'].apply(lambda x: [str(item).strip() for item in x if pd.notna(item) and str(item).strip()] if isinstance(x, list) else [])
             original_rows_after_nan_drop = len(df_std)
             df_std = df_std[df_std['label'].apply(lambda x: len(x) > 0)].reset_index(drop=True)
             rows_dropped_empty_list = original_rows_after_nan_drop - len(df_std)
             if rows_dropped_empty_list > 0: print(f"  Dropped {rows_dropped_empty_list} rows with empty label lists.")


        print(f"  Successfully loaded {len(df_std)} rows from {os.path.basename(filepath)}. Labels are now lists of strings.")
        return df_std

    except FileNotFoundError:
        print(f"Error: Data file somehow not found at {filepath} despite existence check.")
        return None
    except IndexError as e:
         print(f"Error: Problem accessing columns by index in {filepath}. Check indices/config. Details: {e}")
         return None
    except ValueError as e:
         print(f"Error: Problem with data format or content in {filepath}. Details: {e}")
         return None
    except Exception as e:
        print(f"An unexpected error occurred loading {filepath}: {e}")
        import traceback; traceback.print_exc(); return None


def prepare_data(df_train, df_val, df_test):
    """
    Prepares data for multi-label classification: maps labels to ints,
    creates multi-hot vectors, handles train/val/test splitting if needed,
    and calculates class weights for the training set.
    """
    print("\n--- Preparing Data for Multi-Label Classification ---")
    label_col = 'label' # This column now contains lists of label strings

    # Load the fixed 28-label mapping from file
    # We MUST use this map for GoEmotions, don't create from training data
    label_to_int, int_to_label = load_label_mappings()

    if label_to_int is None or int_to_label is None:
        print(f"CRITICAL ERROR: Could not load label mappings from {config.LABEL_MAP_PATH}.")
        print("Please ensure the label map JSON file exists and is valid.")
        sys.exit(1) # Exit if label map is missing/invalid

    n_classes = len(int_to_label)
    print(f"Using fixed label map with {n_classes} classes from {config.LABEL_MAP_PATH}.")
    # print(f"Int to label mapping: {int_to_label}") # Optional: print map

    def create_multihot_labels(label_list, label_to_int, n_classes, row_idx, df_name):
        """Converts a list of label strings into a multi-hot numpy array."""
        if not isinstance(label_list, list):
             print(f"Warning ({df_name} row {row_idx}): Expected list of labels, got {type(label_list)}. Skipping row.")
             return None # Return None to indicate error/skip

        multihot = np.zeros(n_classes, dtype=np.float32)
        unmapped_labels = []
        for label_str in label_list:
            if label_str in label_to_int:
                label_id = label_to_int[label_str]
                if 0 <= label_id < n_classes:
                    multihot[label_id] = 1.0
                else:
                    print(f"Warning ({df_name} row {row_idx}): Label ID {label_id} for '{label_str}' is out of expected range [0, {n_classes-1}]. Skipping label.")
            else:
                unmapped_labels.append(label_str)

        # Note: We don't drop rows just because they have unmapped labels here.
        # We drop rows where the *entire list* processing failed (e.g., input wasn't a list).
        # If unmapped labels are found, it means your label_map.json is likely incomplete
        # for the data you are using, or there's a typo in the data.

        return multihot # Return the multihot array even if some labels were unmapped

    processed_dfs = []
    raw_dfs_input = [('Train', df_train), ('Validation', df_val), ('Test', df_test)]
    # Store processed DFs by name for easier splitting logic later
    processed_df_dict = {}

    for df_name, df in raw_dfs_input:
        if df is None or df.empty:
            processed_df_dict[df_name] = None
            continue

        print(f"Processing {df_name} data ({len(df)} rows)...")
        # Apply multi-hot conversion row by row using list comprehension for speed
        multihot_labels = [
            create_multihot_labels(row[label_col], label_to_int, n_classes, idx, df_name)
            for idx, row in tqdm(df.iterrows(), total=len(df), desc=f"Creating Multi-hot for {df_name}")
        ]

        # Add multi-hot labels to DataFrame
        df['label_multihot'] = multihot_labels

        # Filter out rows where multihot_labels is None (indicating error in create_multihot_labels)
        # or where the resulting multi-hot vector is all zeros (no valid labels found for the text)
        original_len = len(df)
        df = df.dropna(subset=['label_multihot']) # Drop rows where conversion failed
        # Further filter rows where the resulting multi-hot vector is all zeros
        df = df[df['label_multihot'].apply(lambda x: np.sum(x) > 0)].reset_index(drop=True)

        dropped_count = original_len - len(df)
        if dropped_count > 0:
             print(f"Dropped {dropped_count} rows from {df_name} due to errors in multi-hot conversion or resulting in empty label sets.")


        # Replace the list of label strings with the multi-hot numpy array
        df[label_col] = df['label_multihot']
        df.drop(columns=['label_multihot'], inplace=True)

        processed_df_dict[df_name] = df


    # --- Data Splitting (Only if validation/test files were NOT provided/loaded) ---
    df_train_processed = processed_df_dict['Train']
    df_val_processed = processed_df_dict['Validation']
    df_test_processed = processed_df_dict['Test']


    if df_val_processed is None or df_test_processed is None:
        print("\n--- Splitting Processed Training Data ---")
        # If val/test were not loaded, they are None here. We split the processed train data.
        # Use a copy to avoid modifying the original df_train_processed reference during intermediate splits
        df_to_split = df_train_processed.copy() if df_train_processed is not None else pd.DataFrame()
        df_train_intermediate = df_to_split # Start with full processed train data

        if df_val_processed is None and not df_train_intermediate.empty:
            print(f"Splitting validation set ({config.VALIDATION_SPLIT_SIZE*100:.1f}%)...")
            if len(df_train_intermediate) < 2:
                 print("Warning: Not enough data for validation split. Val set empty.")
                 df_val_processed = pd.DataFrame(columns=df_train_intermediate.columns)
            else:
                 if config.STRATIFY_SPLIT:
                     print("Warning: Multi-label stratification is not implemented for splitting. Using simple random split despite STRATIFY_SPLIT=True.")

                 try:
                     df_train_intermediate, df_val_processed = train_test_split(
                         df_train_intermediate,
                         test_size=config.VALIDATION_SPLIT_SIZE,
                         random_state=config.SEED
                         # No stratify for multi-label with simple train_test_split
                     )
                     print(f"  Intermediate Train: {len(df_train_intermediate)}, Val: {len(df_val_processed)}")
                 except ValueError as e:
                      print(f"Warning: Validation split failed ({e}). Val set empty.")
                      df_val_processed = pd.DataFrame(columns=df_train_intermediate.columns)
                 except Exception as e:
                      print(f"Unexpected error during validation split: {e}. Val set empty.")
                      df_val_processed = pd.DataFrame(columns=df_train_intermediate.columns)


        # Update df_train_processed after potential validation split
        df_train_processed = df_train_intermediate # This is the remaining data for the test split/final train


        if df_test_processed is None and not df_train_processed.empty:
             print(f"Splitting test set ({config.TEST_SPLIT_SIZE*100:.1f}% from original)...")
             if len(df_train_processed) < 2:
                  print("Warning: Not enough remaining data for test split. Test set empty.")
                  df_test_processed = pd.DataFrame(columns=df_train_processed.columns)
                  df_train_final = df_train_processed
             else:
                  # Calculate effective split size from the remaining data
                  total_original = len(df_to_split) if not df_to_split.empty else 1 # Avoid division by zero
                  current_train_fraction = len(df_train_processed) / total_original if total_original > 0 else 1.0
                  effective_split_size = config.TEST_SPLIT_SIZE / current_train_fraction if current_train_fraction > 0 else 0.0

                  # Ensure effective_split_size is between 0 and almost 1
                  min_possible_test_size = 1 / (len(df_train_processed) if len(df_train_processed)>0 else 1)
                  max_possible_test_size = 1.0 - (1 / (len(df_train_processed) if len(df_train_processed)>1 else 2)) # Leave at least 1 for train if >1
                  effective_split_size = max(min_possible_test_size if len(df_train_processed) >= 2 else 0.0, min(effective_split_size, max_possible_test_size))


                  if effective_split_size <= 1e-6 or len(df_train_processed) < 2: # Check against small float or insufficient data
                       print(f"Warning: Calculated test split size ({effective_split_size*100:.2f}%) is too small or insufficient data ({len(df_train_processed)}). Test set empty.")
                       df_test_processed = pd.DataFrame(columns=df_train_processed.columns)
                       df_train_final = df_train_processed
                  else:
                       print(f"Splitting test set ({effective_split_size*100:.1f}% from remaining train, aiming for ~{config.TEST_SPLIT_SIZE*100:.1f}% of original)...")
                       if config.STRATIFY_SPLIT:
                            print("Warning: Multi-label stratification is not implemented for splitting. Using simple random split despite STRATIFY_SPLIT=True.")

                       try:
                           df_train_final, df_test_processed = train_test_split(
                               df_train_processed, # Split the data remaining after potential val split
                               test_size=effective_split_size,
                               random_state=config.SEED
                               # No stratify for multi-label
                           )
                           print(f"  Final Train: {len(df_train_final)}, Test: {len(df_test_processed)}")
                       except ValueError as e:
                            print(f"Warning: Test split failed ({e}). Test set empty.")
                            df_test_processed = pd.DataFrame(columns=df_train_processed.columns)
                            df_train_final = df_train_processed
                       except Exception as e:
                            print(f"Unexpected error during test split: {e}. Test set empty.")
                            df_test_processed = pd.DataFrame(columns=df_train_processed.columns)
                            df_train_final = df_train_processed

        else:
            # If both val and test were provided and loaded, df_train_processed is already the final train
             df_train_final = df_train_processed

        df_train_processed = df_train_final
        print("--- Data Splitting Finished ---")


    if df_train_processed is None or df_train_processed.empty:
        raise ValueError("Training data is empty after processing and potential splitting. Cannot proceed.")

    if df_val_processed is not None and df_val_processed.empty: print("Warning: Validation data is empty after processing/splitting.")
    if df_test_processed is not None and df_test_processed.empty: print("Warning: Test data is empty after processing/splitting.")


    # --- Calculate Class Weights for BCEWithLogitsLoss (pos_weight) ---
    print("\nCalculating positive class weights for training data...")
    # Get the multi-hot labels as a single numpy array for easy summation
    train_multihot_labels_np = np.vstack(df_train_processed['label'].tolist())

    # Sum down the columns to get count of positive examples per class
    positive_counts = np.sum(train_multihot_labels_np, axis=0)
    total_samples = len(df_train_processed)
    negative_counts = total_samples - positive_counts

    # Calculate pos_weight = count_neg / count_pos
    # Handle division by zero if positive_counts is 0 for a class
    # A common approach is to set weight to 1 if positive_count is 0
    pos_weight_np = np.where(
        positive_counts > 0,             # Condition: positive_counts > 0
        negative_counts / positive_counts, # Value if True: neg/pos
        1.0                              # Value if False: 1.0 (or some large number, 1.0 is safer)
    ).astype(np.float32) # Ensure dtype is float32

    print(f"Calculated positive counts per class: {positive_counts}")
    print(f"Calculated negative counts per class: {negative_counts}")
    print(f"Calculated pos_weight per class (NumPy): {pos_weight_np}")


    print(f"\nLabel preparation complete. Using {n_classes} classes from loaded map.")
    print(f"Final dataset sizes - Train: {len(df_train_processed)}, Val: {len(df_val_processed) if df_val_processed is not None else 0}, Test: {len(df_test_processed) if df_test_processed is not None else 0}")
    print(f"Final int_to_label mapping: {int_to_label}")


    return df_train_processed, df_val_processed, df_test_processed, label_to_int, int_to_label, n_classes, pos_weight_np


class TransformerDataset(Dataset):
    """PyTorch Dataset for Transformer multi-label classification."""
    def __init__(self, texts, labels_multihot, tokenizer, max_len=config.MAX_LEN):
        self.texts = texts # List of cleaned text strings
        # labels_multihot should be a list of numpy arrays (multi-hot)
        self.labels_multihot = labels_multihot
        self.tokenizer = tokenizer
        self.max_len = max_len

        if not isinstance(self.texts, list):
             raise TypeError("Input 'texts' must be a list.")
        # Allow list or numpy array of numpy arrays
        if not isinstance(self.labels_multihot, (list, np.ndarray)):
             raise TypeError("Input 'labels_multihot' must be a list or numpy array of multi-hot vectors.")

        if len(self.texts) != len(self.labels_multihot):
            raise ValueError(f"Length mismatch: texts ({len(self.texts)}) vs labels_multihot ({len(self.labels_multihot)}).")

        if self.tokenizer is None:
             raise ValueError("TransformerDataset requires a HuggingFace tokenizer.")

        # Ensure labels are numpy arrays for easier handling
        # Check if elements are also numpy arrays or lists to ensure convertibility
        if isinstance(self.labels_multihot, list) and self.labels_multihot:
             if isinstance(self.labels_multihot[0], (list, np.ndarray)):
                try:
                    # Convert list of lists/arrays to single numpy array
                    self.labels_multihot = np.array(self.labels_multihot, dtype=np.float32)
                    # print(f"Converted labels_multihot list to numpy array of shape {self.labels_multihot.shape}") # Debug
                except Exception as e:
                     print(f"Warning: Could not convert labels_multihot list to numpy array: {e}. Proceeding with list.")
                     # If conversion fails, leave as list, but access might be slightly slower
             else:
                  print(f"Warning: labels_multihot is a list but elements are not lists/arrays (e.g., {type(self.labels_multihot[0])}). Check data processing.")


    def __len__(self):
        return len(self.labels_multihot)

    def __getitem__(self, index):
        text = str(self.texts[index])
        # Labels are now multi-hot vectors (numpy arrays or lists)
        label_multihot = self.labels_multihot[index]

        # Convert numpy array or list to torch tensor (float)
        # If self.labels_multihot is a 2D numpy array, label_multihot is 1D np array, convert directly
        # If self.labels_multihot is a list of np arrays, label_multihot is np array, convert directly
        # If self.labels_multihot is a list of lists, label_multihot is list, convert directly
        label = torch.tensor(label_multihot, dtype=torch.float)

        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=self.max_len,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt',
        )

        # Squeeze tensors to remove batch dimension added by return_tensors='pt'
        input_ids = encoding['input_ids'].squeeze(0)
        attention_mask = encoding['attention_mask'].squeeze(0)

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'labels': label # Multi-hot tensor (float)
        }


def create_dataloaders(train_data, val_data, test_data,
                       batch_size=config.TRAIN_BATCH_SIZE, val_batch_size=config.VALID_BATCH_SIZE):
    """Creates PyTorch DataLoaders from datasets."""
    # No custom collate_fn needed for standard tokenized outputs and multi-hot labels
    collate_fn = None
    num_workers = 0 # Keep 0 for simplicity/debugging, increase if data loading is bottleneck

    train_loader = DataLoader(
        train_data, batch_size=batch_size, shuffle=True, num_workers=num_workers,
        collate_fn=collate_fn, pin_memory=True if config.DEVICE == "cuda" else False
    ) if train_data else None

    val_loader = DataLoader(
        val_data, batch_size=val_batch_size, shuffle=False, num_workers=num_workers,
        collate_fn=collate_fn, pin_memory=True if config.DEVICE == "cuda" else False
    ) if val_data else None

    test_loader = DataLoader(
        test_data, batch_size=val_batch_size, shuffle=False, num_workers=num_workers,
        collate_fn=collate_fn, pin_memory=True if config.DEVICE == "cuda" else False
    ) if test_data else None

    print(f"\nDataLoaders created (Batch Size: Train={batch_size}, Val/Test={val_batch_size}).")
    if train_loader is None: print("Warning: Training DataLoader is None.")
    if val_loader is None: print("Warning: Validation DataLoader is None.")
    if test_loader is None: print("Warning: Test DataLoader is None.")

    return train_loader, val_loader, test_loader


def get_data_pipeline():
    """Full data pipeline for Transformer multi-label classification."""
    print("--- Starting Data Pipeline (Transformer Multi-Label Focus) ---")

    # --- 1. Load Raw Data ---
    print("\n--- Loading Raw Data ---")
    # Pass specific column config based on config.py
    df_train = load_raw_data(
        filepath=config.TRAIN_FILE_PATH,
        file_format=config.INPUT_FILE_FORMAT,
        text_col_idx=config.TEXT_COLUMN_INDEX,
        label_col_idx=config.LABEL_COLUMN_INDEX,
        col_names=config.COLUMN_NAMES, # Use names if header=False
        has_header=config.HAS_HEADER # Use header from config
    )

    if df_train is None or df_train.empty:
        raise FileNotFoundError(f"CRITICAL: Training data failed to load or is empty from {config.TRAIN_FILE_PATH}. Cannot proceed.")

    # Load val and test data if paths are provided and files exist
    df_val = None
    if config.VALID_FILE_PATH and os.path.exists(config.VALID_FILE_PATH):
        df_val = load_raw_data(
            filepath=config.VALID_FILE_PATH,
            file_format=config.INPUT_FILE_FORMAT,
            text_col_idx=config.TEXT_COLUMN_INDEX,
            label_col_idx=config.LABEL_COLUMN_INDEX,
            col_names=config.COLUMN_NAMES,
            has_header=config.HAS_HEADER
        )
    elif config.VALID_FILE_PATH:
        print(f"Warning: Validation file path provided ({config.VALID_FILE_PATH}) but file not found. Will split from train data.")

    df_test = None
    if config.TEST_FILE_PATH and os.path.exists(config.TEST_FILE_PATH):
         df_test = load_raw_data(
            filepath=config.TEST_FILE_PATH,
            file_format=config.INPUT_FILE_FORMAT,
            text_col_idx=config.TEXT_COLUMN_INDEX,
            label_col_idx=config.LABEL_COLUMN_INDEX,
            col_names=config.COLUMN_NAMES,
            has_header=config.HAS_HEADER
         )
    elif config.TEST_FILE_PATH:
        print(f"Warning: Test file path provided ({config.TEST_FILE_PATH}) but file not found. Will split from train data.")


    # --- 2. Prepare Data (Mapping, Multi-hot, Splitting, Class Weights) ---
    # prepare_data now returns pos_weight_np
    df_train_processed, df_val_processed, df_test_processed, \
    label_to_int, int_to_label, n_classes, pos_weight_np = prepare_data(
        df_train, df_val, df_test # Pass potentially None dataframes
    )

    if df_train_processed.empty:
         raise ValueError("Training data is empty after preparation (label mapping/multi-hot/splitting). Cannot proceed.")

    # --- 3. Initialize Preprocessor and Tokenizer ---
    print(f"\nInitializing preprocessor: {config.PREPROCESSOR_TYPE}")
    # The BasicTextCleaner is modified to handle emojis
    preprocessor = BasicTextCleaner()
    print(f"Loading HuggingFace Tokenizer: {config.TRANSFORMER_MODEL_NAME}")
    try:
         tokenizer = AutoTokenizer.from_pretrained(config.TRANSFORMER_MODEL_NAME)
         print(f"Tokenizer loaded. Vocab size: {tokenizer.vocab_size}")
    except Exception as e:
         print(f"Fatal Error: Failed to load Transformer tokenizer '{config.TRANSFORMER_MODEL_NAME}': {e}")
         sys.exit(1)


    # --- 4. Apply Cleaning and Create Datasets ---
    print("\nApplying text cleaning to all datasets...")
    # Ensure texts are lists, even if the dataframe is empty
    train_texts = preprocessor.preprocess_batch(df_train_processed['text'].tolist()) if not df_train_processed.empty else []
    val_texts = preprocessor.preprocess_batch(df_val_processed['text'].tolist()) if df_val_processed is not None and not df_val_processed.empty else []
    test_texts = preprocessor.preprocess_batch(df_test_processed['text'].tolist()) if df_test_processed is not None and not df_test_processed.empty else []
    print("Text cleaning complete.")


    print("\nCreating PyTorch Datasets...")
    # Pass the text and the multi-hot label column (which is now df['label'] and contains numpy arrays)
    # Ensure we pass lists of numpy arrays/lists, not the pandas Series itself
    train_dataset = TransformerDataset(
        texts=train_texts,
        labels_multihot=df_train_processed['label'].tolist() if not df_train_processed.empty else [],
        tokenizer=tokenizer,
        max_len=config.MAX_LEN
    ) if not df_train_processed.empty else None

    val_dataset = TransformerDataset(
        texts=val_texts,
        labels_multihot=df_val_processed['label'].tolist() if df_val_processed is not None and not df_val_processed.empty else [],
        tokenizer=tokenizer,
        max_len=config.MAX_LEN
    ) if df_val_processed is not None and not df_val_processed.empty else None

    test_dataset = TransformerDataset(
        texts=test_texts,
        labels_multihot=df_test_processed['label'].tolist() if df_test_processed is not None and not df_test_processed.empty else [],
        tokenizer=tokenizer,
        max_len=config.MAX_LEN
    ) if df_test_processed is not None and not df_test_processed.empty else None


    # --- 5. Create DataLoaders ---
    train_loader, val_loader, test_loader = create_dataloaders(
        train_dataset, val_dataset, test_dataset,
        batch_size=config.TRAIN_BATCH_SIZE,
        val_batch_size=config.VALID_BATCH_SIZE
    )

    print("\n--- Data Pipeline Finished ---")

    # Return all necessary components, including pos_weight_np
    return train_loader, val_loader, test_loader, label_to_int, int_to_label, n_classes, tokenizer, pos_weight_np
